window.SOR_APP_DATA = [
  {
    id: "mould-cold-corner",
    title: "Mould to external wall corner",
    category: "Findings",
    tags: ["mould", "corner", "cold bridge", "external wall"],
    tenantText: "Mould growth was noted to a colder external wall corner. This can happen where moisture in the air settles on a cold surface, particularly during colder months or where airflow is restricted.",
    internalWording: "Mould noted to external wall corner. Consider mould wash and thermal/ventilation improvements subject to survey findings.",
    actionType: "finding"
  },
  {
    id: "mould-window-reveal",
    title: "Mould around window reveal",
    category: "Findings",
    tags: ["mould", "window", "reveal", "condensation"],
    tenantText: "Mould staining was noted around the window reveal. This area can be prone to condensation because the surface temperature around openings is often lower than the rest of the wall.",
    internalWording: "Mould noted to window reveal. Check ventilation, seals, trickle vents and cold bridging.",
    actionType: "finding"
  },
  {
    id: "mould-ceiling-perimeter",
    title: "Mould to ceiling perimeter",
    category: "Findings",
    tags: ["mould", "ceiling", "perimeter", "cold bridge"],
    tenantText: "Mould was noted around the ceiling perimeter. This can be linked to colder junctions where the ceiling meets an outside wall, allowing moisture to settle on the surface.",
    internalWording: "Mould noted to ceiling/wall junction. Check insulation, ventilation and cold bridging.",
    actionType: "finding"
  },
  {
    id: "bathroom-ceiling-mould",
    title: "Bathroom ceiling mould",
    category: "Findings",
    tags: ["bathroom", "ceiling", "fan", "mould"],
    tenantText: "Mould was noted to the bathroom ceiling. Bathrooms produce high levels of moisture, so effective extraction and regular ventilation are important to reduce the risk of mould returning.",
    internalWording: "Bathroom ceiling mould noted. Check extractor performance and ceiling condition.",
    actionType: "finding"
  },
  {
    id: "behind-furniture",
    title: "Mould behind furniture",
    category: "Findings",
    tags: ["furniture", "airflow", "mould"],
    tenantText: "Mould was noted behind or near furniture. Furniture placed close to external walls can restrict airflow and make the surface colder, which may increase the chance of condensation forming.",
    internalWording: "Mould noted behind/near furniture. Include advice without placing sole responsibility on tenant.",
    actionType: "finding"
  },
  {
    id: "no-active-mould",
    title: "No active mould seen at visit",
    category: "Findings",
    tags: ["no mould", "clear", "monitor"],
    tenantText: "No active mould growth was identified at the time of inspection. The area should be monitored, especially during colder weather or after periods of high moisture.",
    internalWording: "No active mould seen at inspection. Monitor and reattend if issue returns.",
    actionType: "finding"
  },
  {
    id: "cold-bridging",
    title: "Likely cold bridging",
    category: "Likely causes",
    tags: ["cold bridge", "thermal", "condensation"],
    tenantText: "The pattern seen is consistent with colder sections of the building fabric. When warm, moist air meets these colder surfaces, condensation can form and contribute to mould growth.",
    internalWording: "Pattern consistent with cold bridging/thermal deficiency.",
    actionType: "cause"
  },
  {
    id: "poor-ventilation",
    title: "Poor background ventilation",
    category: "Likely causes",
    tags: ["ventilation", "humidity", "condensation"],
    tenantText: "Ventilation appears limited, which can allow moisture to remain in the property for longer. Improving background ventilation should help reduce the risk of condensation and mould.",
    internalWording: "Ventilation appears insufficient. Consider passive vent, extractor upgrade or tenant advice as appropriate.",
    actionType: "cause"
  },
  {
    id: "extractor-faulty",
    title: "Extractor fan not working / poor performance",
    category: "Likely causes",
    tags: ["fan", "extractor", "bathroom", "kitchen"],
    tenantText: "The extractor fan was not working correctly or did not appear to be performing effectively. This can allow moisture from bathing, showering or cooking to remain in the room.",
    internalWording: "Check extractor fan operation and airflow. Renew or upgrade if defective/insufficient.",
    actionType: "cause"
  },
  {
    id: "leak-suspected",
    title: "Leak suspected",
    category: "Likely causes",
    tags: ["leak", "plumbing", "damp"],
    tenantText: "A possible leak or water ingress issue was identified. Further repair or investigation may be required to confirm and resolve the source of moisture.",
    internalWording: "Leak/water ingress suspected. Arrange further investigation/repair as required.",
    actionType: "cause"
  },
  {
    id: "concrete-bridging-dpc",
    title: "Concrete / paving breaching DPC",
    category: "External defects",
    tags: ["concrete", "paving", "DPC", "ground level", "cut back"],
    code: "003015 / 048003",
    description: "PATH/BASE: REMOVE AND INFILL WITH GRAVEL or lower insitu paving prior to DPC injection",
    uom: "SM",
    rate: "£73.7330 / £130.2972",
    tenantText: "External concrete or paving appears too high against the wall and may be bridging the damp proof course. This can allow moisture to affect the wall, so the external level should be reduced or cut back.",
    internalWording: "Cut back/lower concrete paving adjacent to property to provide clearance below DPC. Consider gravel margin and falls away from building.",
    actionType: "work"
  },
  {
    id: "path-base-remove",
    title: "Remove concrete path/base",
    category: "External works",
    tags: ["concrete", "path", "remove", "break out"],
    code: "003013",
    description: "PATH/BASE: REMOVE",
    uom: "SM",
    rate: "£32.4557",
    tenantText: "A section of concrete or hardstanding needs to be removed to resolve the issue identified during the inspection.",
    internalWording: "Break up and remove existing concrete path/base and bedding. Remove waste and leave ready for new finish.",
    actionType: "work"
  },
  {
    id: "brick-sealer",
    title: "Apply brick sealer / masonry sealer",
    category: "External works",
    tags: ["brick", "seal", "sealer", "masonry", "waterproof"],
    code: "436082 / 436104",
    description: "WALLS: APPLY SEALER 2 COATS MASONRY - BRICK / WALLS: SEALER - 2 COATS EXTERNAL MASONRY W/PROOFER",
    uom: "SM",
    rate: "£12.5967 / £15.7647",
    tenantText: "The external wall requires treatment with a suitable masonry sealer to help reduce water absorption and protect the wall surface.",
    internalWording: "Prepare brickwork and apply suitable masonry/brick sealer, two coats, to affected external area.",
    actionType: "work"
  },
  {
    id: "door-cill-repair",
    title: "Repair / renew door cill",
    category: "Joinery",
    tags: ["door", "cill", "threshold", "repair"],
    code: "342315",
    description: "FRAME: RENEW HARDWOOD CILL",
    uom: "NO",
    rate: "£87.1645",
    tenantText: "The door cill requires repair or renewal to prevent water penetration and maintain the condition of the doorway.",
    internalWording: "Remove defective door cill and renew hardwood cill, including making good and decoration to match existing where required.",
    actionType: "work"
  },
  {
    id: "thermal-board-25-wall",
    title: "Install 25mm thermal board to wall",
    category: "Thermal works",
    tags: ["thermal", "board", "dry line", "cold bridge", "insulated plasterboard"],
    code: "427009",
    description: "WALL: DRY LINE 25MM THERMALBOARD",
    uom: "SM",
    rate: "£72.2032",
    tenantText: "Insulated plasterboard is recommended to improve the surface temperature of the affected wall and reduce the risk of condensation and mould returning.",
    internalWording: "Dry line affected wall with 25mm thermalboard, including associated preparation and making good.",
    actionType: "work"
  },
  {
    id: "thermal-board-45-wall",
    title: "Install 45mm thermal board to wall",
    category: "Thermal works",
    tags: ["thermal", "board", "45mm", "dry line"],
    code: "427011",
    description: "WALL: DRY LINE 45MM THERMALBOARD",
    uom: "SM",
    rate: "£97.8885",
    tenantText: "A thicker insulated plasterboard system is recommended to improve the thermal performance of the affected wall and reduce recurring condensation risk.",
    internalWording: "Dry line affected wall with 45mm thermalboard, including associated preparation and making good.",
    actionType: "work"
  },
  {
    id: "ceiling-thermal-board",
    title: "Install thermal board to ceiling",
    category: "Thermal works",
    tags: ["ceiling", "thermal", "board", "insulation"],
    code: "427005 / 427007",
    description: "CEILING: DRY LINE 12.5MM / 25MM THERMALBOARD",
    uom: "SM",
    rate: "£72.8607 / £98.7584",
    tenantText: "Insulated plasterboard is recommended to the affected ceiling area to improve surface temperature and reduce condensation risk.",
    internalWording: "Dry line affected ceiling with suitable thermalboard, including battens/screw fixing where applicable and making good.",
    actionType: "work"
  },
  {
    id: "refix-thermal-board",
    title: "Refix thermal board with mechanical fixings",
    category: "Thermal works",
    tags: ["refix", "thermal", "mechanical fixings", "board"],
    code: "Non-SOR / use 427009 or 427011 if full dry lining",
    description: "No exact standalone refix code identified",
    uom: "TBC",
    rate: "TBC",
    tenantText: "Existing insulated board requires re-securing to ensure the finish is stable and performs as intended.",
    internalWording: "Re-secure existing thermal board using suitable mechanical fixings in accordance with manufacturer guidance. Raise as non-SOR if only refixing is required.",
    actionType: "work"
  },
  {
    id: "wc-remove-reinstate",
    title: "Remove and reinstate WC",
    category: "Plumbing",
    tags: ["WC", "toilet", "remove", "reinstate"],
    code: "630573",
    description: "WC CISTERN/PAN: OVERHAUL ANY TYPE",
    uom: "IT",
    rate: "£65.5415",
    tenantText: "The toilet may need to be temporarily removed and reinstated to allow the repair works to be completed safely and properly.",
    internalWording: "Remove and refix existing WC pan/cistern as required to facilitate works. Remake soil/flush connections, reinstate supply, test and leave operational.",
    actionType: "work"
  },
  {
    id: "wc-remove-complete",
    title: "Remove WC suite complete",
    category: "Plumbing",
    tags: ["WC", "toilet", "remove", "suite"],
    code: "630514",
    description: "WC SUITE: REMOVE COMPLETE",
    uom: "NO",
    rate: "£44.04",
    tenantText: "The existing toilet suite requires removal as part of the proposed repair works.",
    internalWording: "Remove WC suite complete, disconnect pan/cistern, cap/seal pipework and remove waste.",
    actionType: "work"
  },
  {
    id: "boxing-remove-refix",
    title: "Remove and refix boxing",
    category: "Joinery",
    tags: ["boxing", "duct", "remove", "refix"],
    code: "420503 / 387017",
    description: "BOXING: REMOVE AND REFIX EXISTING / DUCT: REMOVE REFIX CASING FOR EMPLOYER INSPECTION",
    uom: "LM",
    rate: "£14.3327 / £11.2212",
    tenantText: "Existing boxing may need to be carefully removed and reinstated to allow access to concealed pipework or affected areas.",
    internalWording: "Carefully remove existing boxing/duct casing, set aside and refix on completion of works.",
    actionType: "work"
  },
  {
    id: "access-panel-boxing",
    title: "Form access panel in existing boxing",
    category: "Joinery",
    tags: ["boxing", "access panel", "duct"],
    code: "387019",
    description: "DUCT: FORM ACCESS PANEL IN EXISTING",
    uom: "IT",
    rate: "£51.9326",
    tenantText: "An access panel is recommended so concealed services can be inspected or maintained without removing the full boxing in future.",
    internalWording: "Form suitable access panel in existing duct/boxing to enable inspection/maintenance.",
    actionType: "work"
  },
  {
    id: "hack-off-render",
    title: "Hack off render / render plinth",
    category: "External works",
    tags: ["render", "plinth", "hack off", "external"],
    code: "421003 / 421001",
    description: "WALL: HACK OFF RENDER / WALL: HACK OFF RENDER IN PATCH",
    uom: "SM / IT",
    rate: "£20.0266 / £25.0334",
    tenantText: "Defective render needs to be removed so the wall can dry and any necessary repairs can be carried out to the background surface.",
    internalWording: "Hack off defective render/render plinth, rake out and prepare background, remove waste and debris.",
    actionType: "work"
  },
  {
    id: "socket-remove-refix",
    title: "Remove and reinstate socket",
    category: "Electrical",
    tags: ["socket", "electrical", "remove", "refix"],
    code: "861501",
    description: "SOCKET: RENEW FLUSH BOX",
    uom: "NO",
    rate: "£19.1491",
    tenantText: "An electrical socket may need to be temporarily removed and reinstated to allow repair works to be completed. The socket should be tested after reinstatement.",
    internalWording: "Isolate, remove and set aside existing socket plate, reinstate/refix on completion, remake connections, test and make good.",
    actionType: "work"
  },
  {
    id: "cwst-insulation",
    title: "Insulate cold water storage tank",
    category: "Plumbing",
    tags: ["cold water storage tank", "CWST", "tank", "insulation"],
    code: "670001 / 670003",
    description: "TANK: RENEW INSULATION TO NE 113 LITRE / NE 227 LITRE",
    uom: "NO",
    rate: "£23.2536 / £26.5745",
    tenantText: "The cold water storage tank requires insulation to reduce heat loss and help protect the stored water system.",
    internalWording: "Supply and securely fix suitable insulating jacket to cold water storage tank, size to suit.",
    actionType: "work"
  },
  {
    id: "strip-wallpaper-walls",
    title: "Strip wallpaper from walls",
    category: "Decoration",
    tags: ["wallpaper", "strip", "walls"],
    code: "451051 / 451052",
    description: "ROOM: STRIP WALLPAPER UP TO 20SM / OVER 20SM CEILING AREA",
    uom: "IT / SM",
    rate: "£120.1601 / £6.6119",
    tenantText: "Wallpaper needs to be stripped from the affected walls so the surface can be properly prepared for treatment or redecoration.",
    internalWording: "Strip wallpaper from walls, including preparation for redecoration.",
    actionType: "work"
  },
  {
    id: "strip-wallpaper-ceiling",
    title: "Strip wallpaper from ceiling",
    category: "Decoration",
    tags: ["wallpaper", "strip", "ceiling"],
    code: "451007 / 451015",
    description: "ROOM: STRIP PAPER UP TO 20SM CEILING AREA / OVER 20SM CEILING AREA",
    uom: "IT / SM",
    rate: "£128.6148 / £6.6119",
    tenantText: "Wallpaper needs to be stripped from the affected ceiling area so the surface can be properly prepared for treatment or redecoration.",
    internalWording: "Strip wallpaper from ceiling, including preparation for redecoration.",
    actionType: "work"
  },
  {
    id: "floor-protection",
    title: "Temporary floor protection",
    category: "Protection",
    tags: ["floor", "protection", "correx", "temporary"],
    code: "Non-SOR",
    description: "No dedicated temporary floor protection code identified",
    uom: "TBC",
    rate: "TBC",
    tenantText: "Temporary floor protection should be used during the works to help protect existing floor finishes in the working area.",
    internalWording: "Supply and lay suitable temporary floor protection such as Correx/roll-and-stroll/taped protective sheeting. Raise as non-SOR where required.",
    actionType: "work"
  },
  {
    id: "helibar",
    title: "Helibar / helical bar crack stitching",
    category: "Structural / non-SOR",
    tags: ["helibar", "helical", "crack", "stitching"],
    code: "Non-SOR / 101901 closest",
    description: "WALL: REPAIR FRACTURE is closest but does not exactly describe Helibar installation",
    uom: "LM",
    rate: "TBC / £76.8204 closest",
    tenantText: "Crack repair works may be required to strengthen the affected masonry and reduce the risk of further movement or water penetration.",
    internalWording: "Chase out mortar bed joints, install stainless-steel helical reinforcement bars in structural repair grout, repoint and make good. Raise as non-SOR or engineer-specified item.",
    actionType: "work"
  },
  {
    id: "mould-wash",
    title: "Mould wash treatment",
    category: "Treatment",
    tags: ["mould wash", "treatment", "clean"],
    code: "TBC",
    description: "Mould wash treatment code to confirm from full SOR",
    uom: "TBC",
    rate: "TBC",
    tenantText: "A mould wash treatment is recommended to clean and treat the affected surfaces before any further making good or redecoration.",
    internalWording: "Carry out mould wash treatment to affected surfaces in accordance with specification.",
    actionType: "work"
  },
  {
    id: "tenant-advice-airflow",
    title: "Airflow behind furniture advice",
    category: "Tenant advice",
    tags: ["advice", "furniture", "airflow"],
    tenantText: "Where possible, keeping furniture slightly away from external walls can help air move around colder areas. This is not being treated as the sole cause of the issue, but it may help reduce the chance of mould returning after repairs are completed.",
    internalWording: "Provide balanced airflow advice without apportioning blame.",
    actionType: "advice"
  },
  {
    id: "tenant-advice-ventilation",
    title: "Ventilation use advice",
    category: "Tenant advice",
    tags: ["advice", "ventilation", "windows", "fans"],
    tenantText: "Using available ventilation, such as extractor fans, trickle vents or short periods of window opening where safe and practical, can help remove moisture from the home.",
    internalWording: "Provide practical ventilation advice alongside repairs.",
    actionType: "advice"
  }
];
